
"""
Sherlock Pro - Results Exporter
"""

import json
import csv
from pathlib import Path
from typing import Dict


def export_results(results: Dict, filepath: str, format: str = "json"):
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)

    if format == "json":
        with open(path, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2, default=str)

    elif format == "csv":
        with open(path, "w", newline="", encoding="utf-8") as f:
            if results["accounts"]:
                writer = csv.DictWriter(f, fieldnames=results["accounts"][0].keys())
                writer.writeheader()
                writer.writerows(results["accounts"])

    elif format == "html":
        html_content = generate_html_report(results)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html_content)


def generate_html_report(results: Dict) -> str:
    accounts_html = ""
    for account in results["accounts"]:
        accounts_html += f"""
        <div class="account-card">
            <h3>{account['platform']}</h3>
            <p><a href="{account['url']}" target="_blank">{account['url']}</a></p>
            <p class="meta">Response Time: {account.get('response_time', 'N/A')}s</p>
        </div>
        """

    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sherlock Pro - {results['username']}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eee;
            min-height: 100vh;
            padding: 40px;
        }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        h1 {{ color: #00d4ff; font-size: 2.5em; margin-bottom: 10px; }}
        .subtitle {{ color: #aaa; margin-bottom: 30px; }}
        .summary {{ 
            background: rgba(255,255,255,0.05);
            padding: 25px;
            border-radius: 15px;
            margin-bottom: 30px;
            border: 1px solid rgba(255,255,255,0.1);
        }}
        .summary-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }}
        .stat {{ text-align: center; }}
        .stat-value {{ font-size: 2em; color: #e94560; font-weight: bold; }}
        .stat-label {{ color: #aaa; font-size: 0.9em; margin-top: 5px; }}
        .account-card {{
            background: rgba(255,255,255,0.05);
            padding: 20px;
            margin: 15px 0;
            border-radius: 12px;
            border-left: 4px solid #00d4ff;
            transition: transform 0.2s;
        }}
        .account-card:hover {{ transform: translateX(10px); }}
        .account-card h3 {{ color: #e94560; margin-bottom: 10px; }}
        .account-card a {{ color: #00d4ff; text-decoration: none; }}
        .account-card a:hover {{ text-decoration: underline; }}
        .meta {{ color: #888; font-size: 0.85em; margin-top: 8px; }}
        .footer {{ text-align: center; margin-top: 40px; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Sherlock Pro</h1>
        <p class="subtitle">OSINT Investigation Report</p>

        <div class="summary">
            <div class="summary-grid">
                <div class="stat">
                    <div class="stat-value">{results['username']}</div>
                    <div class="stat-label">Username</div>
                </div>
                <div class="stat">
                    <div class="stat-value">{results['total_platforms']}</div>
                    <div class="stat-label">Platforms</div>
                </div>
                <div class="stat">
                    <div class="stat-value">{results['found_accounts']}</div>
                    <div class="stat-label">Found</div>
                </div>
                <div class="stat">
                    <div class="stat-value">{results['investigation_time']}s</div>
                    <div class="stat-label">Time</div>
                </div>
            </div>
        </div>

        <h2 style="color: #00d4ff; margin-bottom: 20px;">Discovered Accounts</h2>
        {accounts_html}

        <div class="footer">
            <p>Generated by Sherlock Pro v2.0.0 | Open Source OSINT Tool</p>
        </div>
    </div>
</body>
</html>
"""
